# The main purpose for this build script is to start Jenkins CI server

sudo: required

language: python
python:
  - "3.6"
cache: pip

services:
  - docker

script:
  - ./scripts/start-jenkins-ci.sh

