version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    env_file:
    - .env
    hostname: web
    command: ["./docker-entrypoint-web.sh"]
    volumes:
      # Mount src to app
      - ./:/app
      # Mount entrypoint.sh to run in container
      - ./docker-entrypoint-web.sh:/app/docker-entrypoint-web.sh
      #- ./docker-entrypoint-celery-beat.sh:/app/docker-entrypoint-celery-beat.sh
    # ports:
    #   - "8000:8000"
    expose:
      - "8000"
    #depends_on:
    #  - db
    restart: "no"