version: "3"

services:
  mqtt:
    image: eclipse-mosquitto:1.4.12
    restart: "no"

  db:
    image: postgres:9.6
    restart: "no"
    env_file: .env

  redis:
    image: redis:4-32bit
    env_file: .env
    command: redis-server --appendonly yes --requirepass $REDIS_PASSWORD
    restart: "no"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: faulty/ngip-middleware-web
    stdin_open: true
    tty: true
    env_file:
      - .env
    hostname: web
    depends_on:
      - db
      - redis
      - mqtt
    command: ["./docker-entrypoint-web.sh"]
    volumes:
      # Mount src to app
      - ./:/app
      # Mount entrypoint.sh to run in container
      - ./docker-entrypoint-web.sh:/app/docker-entrypoint-web.sh
      #- ./docker-entrypoint-celery-beat.sh:/app/docker-entrypoint-celery-beat.sh
    ports:
      - "8000:8000"
    expose:
      - "8000"
    restart: "no"